[package]
name = "soon-l1-chain-provider"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
soon-derive = { workspace = true }
soon-primitives = { workspace = true }

tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
futures = { workspace = true}
async-trait = { workspace = true }
lru = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

#alloy
alloy = { workspace = true, features = ["full", "reqwest"] }
alloy-rlp = { workspace = true }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-transport.workspace = true
alloy-primitives = { workspace = true }

#op-alloy
op-alloy-consensus = { workspace = true }
op-alloy-rpc-types = { workspace = true }
op-alloy-network = { workspace = true }
op-alloy-rpc-types-engine = { workspace = true }
