[workspace]
members = [
    "bridge-program",
    "l1-block-info-program",
    "spl-noop-program",
    "test-program",
]
resolver = "2"

[workspace.dependencies]
solana-program = "=2.0.14"
solana-sdk = "=2.0.14"

[patch.crates-io]
solana-program = { git = "https://github.com/soonlabs/agave", branch = "feat/risc0-zkvm" }
solana-sdk = { git = "https://github.com/soonlabs/agave", branch = "feat/risc0-zkvm" }
solana-zk-token-sdk = { git = "https://github.com/soonlabs/agave", branch = "feat/risc0-zkvm" }

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
