use std::collections::BTreeMap;
use std::sync::Arc;
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{LITESVM_FPVM_ELF, LITESVM_FPVM_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use solana_sdk::pubkey::Pubkey;
use solana_sdk::signature::Keypair;
use soon_node::derive::mock::MockInstant;
use soon_node::executor::{ExecutorOperator, SharedExecutor};
use soon_node::node::producer::Producer;
use soon_node::node::tests::{init_soon_genesis, new_derive_block_with_mock_l1, new_producer, MockEthL1Node};
use soon_primitives::blocks::{BlockInfo, RawBlock, L2BlockInfo};
use crossbeam_channel::Receiver;
use solana_sdk::account::AccountSharedData;
use soon_storage::error::Error;
use litesvm::{L2Block, L2Transaction};
use fraud_executor::accounts::SoonAccounts;
use serde::{Deserialize, Serialize};
use solana_sdk::clock::Slot;
use solana_sdk::hash::Hash;
use soon_node::derive::driver::L2ChainProviderImmutable;
use soon_primitives::l2blocks::{L2Block as SoonL2Block, L2Transaction as SoonL2Transaction};

type AccountPairs = Vec<(Pubkey, AccountSharedData)>;

fn main() -> anyhow::Result<()> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // initialize soon
    let temp_file = tempfile::tempdir()?;
    let (mut producer, complete_receiver) =
        new_soon(temp_file.path(), None)?;
    // record slot 0 witness
    let mut witness_0 = fetch_witness_from_soon(producer.get_executor())?;

    // produce slot 1
    let mut l1_node = MockEthL1Node::new(1, 10);
    let _deposit_to = produce_slot_1(&mut l1_node, &mut producer, &complete_receiver)?;
    // record slot 1 witness
    let witness_1 = fetch_witness_from_soon(producer.get_executor())?;
    // let state_root_1 = SoonAccounts::from(witness_1.soon_accounts).state_root();
    let block_1 = fetch_l2_block_from_soon(producer.get_executor())?;
    let block_data_1 = bincode::serialize(&block_1)?;

    // override witness 0
    witness_0.leader = witness_1.leader;
    witness_0.clock_timestamp = witness_1.clock_timestamp;
    let witness_data_0 = bincode::serialize(&witness_0)?;

    let env = ExecutorEnv::builder()
        .write_frame(&witness_data_0)
        .write_frame(&block_data_1)
        .build()?;

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, LITESVM_FPVM_ELF)?;

    // extract the receipt.
    let receipt = prove_info.receipt;

    // Verify the proof.
    let diff_accounts: AccountPairs = receipt.journal.decode()?;
    let mut accounts_map = witness_0.soon_accounts.into_iter().collect::<BTreeMap<_, _>>();
    accounts_map.extend(diff_accounts);

    let accounts_map_origin = witness_1.soon_accounts.into_iter().collect::<BTreeMap<_, _>>();

    for (pubkey, expect_account) in accounts_map_origin.iter() {
        if let Some(actual_account) = accounts_map.get_mut(pubkey) {
            if actual_account != expect_account {
                println!("account mismatch for {}", pubkey);
                println!("  expect: {:?}", expect_account);
                println!("  actual: {:?}", actual_account);
            }
        } else {
            println!("missing account for {}", pubkey);
        }
    }

    // let new_state_root = SoonAccounts::from(accounts_map).state_root();
    // assert_eq!(new_state_root, state_root_1, "state root mismatch");

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(LITESVM_FPVM_ID)?;

    Ok(())
}

fn new_soon(
    path: &std::path::Path,
    relative_to_soon: Option<&str>,
) -> anyhow::Result<(
    Producer<SharedExecutor, MockInstant>,
    Receiver<(L2BlockInfo, Option<BlockInfo>)>,
)> {
    let identity = Arc::new(Keypair::new());
    println!("dir: {:?}", std::env::var("CARGO_MANIFEST_DIR")
        .ok()
        .map_or_else(
            || std::env::current_dir().ok(),
            |s| Some(std::path::PathBuf::from(s)),
        ));
    init_soon_genesis(
        path,
        &identity,
        true,
        Some(
            std::env::var("CARGO_MANIFEST_DIR")
                .ok()
                .map_or_else(
                    || std::env::current_dir().ok(),
                    |s| Some(std::path::PathBuf::from(s)),
                )
                .unwrap()
                .join(relative_to_soon.unwrap_or("../../../../../../"))
                .join("soon/node/programs/target/deploy"),
        ),
    )?;
    let (producer, _, complete_receiver) = new_producer(path, identity.clone())?;

    Ok((producer, complete_receiver))
}

fn produce_slot_1(
    l1_node: &mut MockEthL1Node,
    producer: &mut Producer<SharedExecutor, MockInstant>,
    complete_receiver: &Receiver<(L2BlockInfo, Option<BlockInfo>)>,
) -> anyhow::Result<Pubkey> {
    let deposit_to = Pubkey::new_unique();
    let derive_block_1 = new_derive_block_with_mock_l1(l1_node, deposit_to);
    let raw = RawBlock::try_init(derive_block_1, 0, &Default::default())?;
    producer.mine_with_block(Some(raw))?;
    complete_receiver.try_recv()?;

    Ok(deposit_to)
}

fn fetch_witness_from_soon(executor: &SharedExecutor) -> soon_node::Result<Witness> {
    executor.storage_query(|s| {
        let bank = s.current_bank();
        let soon_accounts = bank
            .get_all_accounts(false)
            .map_err(|e| Error::FraudproofError(e.to_string()))?
            .into_iter()
            .map(|(pubkey, account, _slot)| (pubkey, account))
            .collect::<Vec<_>>();
        let parent_slot = bank.slot();
        let parent_bank_hash = bank.hash();
        let clock_timestamp = bank.clock().unix_timestamp;
        let leader = *bank.collector_id();

        Ok(Witness {
            soon_accounts,
            parent_slot,
            parent_bank_hash,
            clock_timestamp,
            leader,
        })
    })
}

fn fetch_l2_block_from_soon(executor: &SharedExecutor) -> anyhow::Result<L2Block> {
    let slot = executor.latest_slot()?;
    let block_with_entries = executor.block_by_number_immut(slot)?;
    let l2_block: SoonL2Block = block_with_entries.try_into()?;
    Ok(soon_l2_block_to_litesvm_l2_block(l2_block))
}

fn soon_l2_block_to_litesvm_l2_block(l2_block: SoonL2Block) -> L2Block {
    let l2_txs = l2_block
        .transactions
        .into_iter()
        .map(|tx| match tx {
            SoonL2Transaction::Head(index, tx) => L2Transaction::Head(index, tx),
            SoonL2Transaction::Body(tx) => L2Transaction::Body(tx),
        })
        .collect();
    L2Block(l2_txs)
}

#[derive(Debug, Serialize, Deserialize)]
struct Witness {
    soon_accounts: AccountPairs,
    parent_slot: Slot,
    parent_bank_hash: Hash,
    clock_timestamp: i64,
    leader: Pubkey,
}