use std::sync::Arc;
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{LITESVM_FPVM_ELF, LITESVM_FPVM_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use solana_sdk::pubkey::Pubkey;
use solana_sdk::signature::Keypair;
use soon_node::derive::mock::MockInstant;
use soon_node::executor::{ExecutorOperator, SharedExecutor};
use soon_node::node::producer::Producer;
use soon_node::node::tests::{init_soon_genesis, new_derive_block_with_mock_l1, new_producer, MockEthL1Node};
use soon_primitives::blocks::{BlockInfo, RawBlock, L2BlockInfo};
use crossbeam_channel::Receiver;
use solana_sdk::account::AccountSharedData;
use solana_sdk::signer::Signer;
use soon_storage::error::Error;
use litesvm::{ParentInfo, L2Block};
use serde::{Deserialize, Serialize};
use soon_node::derive::driver::L2ChainProviderImmutable;

type AccountPairs = Vec<(Pubkey, AccountSharedData)>;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // initialize soon
    let temp_file = tempfile::tempdir()?;
    let (mut producer, complete_receiver) =
        new_soon(temp_file.path(), None)?;
    // record slot 0 witness
    let witness_0 = fetch_witness_from_soon(producer.get_executor())?;
    let witness_data_0 = bincode::serialize(&witness_0)?;

    // produce slot 1
    let mut l1_node = MockEthL1Node::new(1, 10);
    let _deposit_to = produce_slot_1(&mut l1_node, &mut producer, &complete_receiver)?;
    // record slot 1 witness
    let witness_1 = fetch_witness_from_soon(producer.get_executor())?;
    let block_1 = fetch_l2_block_from_soon(producer.get_executor()).await?;
    let block_data_1 = bincode::serialize(&block_1)?;

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // A default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let env = ExecutorEnv::builder()
        .write_frame(&witness_data_0)
        .write_frame(&block_data_1)
        .build()?;

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, LITESVM_FPVM_ELF)?;

    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.

    // For example:
    let output: usize = receipt.journal.decode()?;
    println!("output: {}", output);

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(LITESVM_FPVM_ID)?;

    Ok(())
}

fn new_soon(
    path: &std::path::Path,
    relative_to_soon: Option<&str>,
) -> anyhow::Result<(
    Producer<SharedExecutor, MockInstant>,
    Receiver<(L2BlockInfo, Option<BlockInfo>)>,
)> {
    let identity = Arc::new(Keypair::new());
    init_soon_genesis(
        path,
        &identity,
        true,
        Some(
            std::env::var("CARGO_MANIFEST_DIR")
                .ok()
                .map_or_else(
                    || std::env::current_dir().ok(),
                    |s| Some(std::path::PathBuf::from(s)),
                )
                .unwrap()
                .join(relative_to_soon.unwrap_or("../../.."))
                .join("soon/node/programs/target/deploy"),
        ),
    )?;
    let (producer, _, complete_receiver) = new_producer(path, identity.clone())?;

    Ok((producer, complete_receiver))
}

fn produce_slot_1(
    l1_node: &mut MockEthL1Node,
    producer: &mut Producer<SharedExecutor, MockInstant>,
    complete_receiver: &Receiver<(L2BlockInfo, Option<BlockInfo>)>,
) -> anyhow::Result<Pubkey> {
    let deposit_to = Pubkey::new_unique();
    let derive_block_1 = new_derive_block_with_mock_l1(l1_node, deposit_to);
    let raw = RawBlock::try_init(derive_block_1, 0, &Default::default())?;
    producer.mine_with_block(Some(raw))?;
    complete_receiver.try_recv()?;

    Ok(deposit_to)
}

fn fetch_witness_from_soon(executor: &SharedExecutor) -> soon_node::Result<Witness> {
    executor.storage_query(|s| {
        let bank = s.current_bank();
        let soon_accounts = bank
            .get_all_accounts(false)
            .map_err(|e| Error::FraudproofError(e.to_string()))?
            .into_iter()
            .map(|(pubkey, account, _slot)| (pubkey, account))
            .collect::<Vec<_>>();
        let parent_info = ParentInfo {
            slot: s.current_slot(),
            bank_hash: bank.hash(),
            fee_rate_governor: bank.fee_rate_governor.clone(),
            signature_count: bank.signature_count(),
        };
        let clock_timestamp = bank.clock().unix_timestamp;
        let leader = *bank.collector_id();

        Ok(Witness {
            soon_accounts,
            parent_info,
            clock_timestamp,
            leader,
        })
    })
}

async fn fetch_l2_block_from_soon(executor: &SharedExecutor) -> soon_node::Result<L2Block> {
    let slot = executor.latest_slot()?;
    let l2_block = executor.block_by_number_immut(slot).await?;
    Ok(l2_block.into())
}

#[derive(Debug, Serialize, Deserialize)]
struct Witness {
    soon_accounts: AccountPairs,
    parent_info: ParentInfo,
    clock_timestamp: i64,
    leader: Pubkey,
}